name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Decode and create .env file
      run: |
        echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
        
    - name: Pull Docker image from ECR
      run: sudo docker pull ${{ secrets.ECR_REPO }}:latest

    - name: Delete old Docker container
      run: sudo docker rm -f ${{ secrets.CONTAINER_NAME }} || true

    - name: Run Docker Container
      run: sudo docker run -d -p 80:3000 --name ${{ secrets.CONTAINER_NAME }} --env-file .env ${{ secrets.ECR_REPO }}:latest
