name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Decode and create .env file
      run: |
        echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}


    - name: Build the Docker image
      run: docker build -t ${{ secrets.ECR_REPO }}:latest .

    - name: Push to AWS ECR
      run: docker push ${{ secrets.ECR_REPO }}:latest
